- name: playbook 1
  hosts: all
  gather_facts: no
  connection: network_cli

  vars_prompt:
    - name: 'username'
      prompt: 'Enter username'
      default: 'cisco'
      private: false
      unsafe: true

    - name: 'password'
      prompt: 'Enter password'
      default: 'cisco'
      private: true
#      confirm: true
      unsafe: true

  vars:
    ansible_user: '{{ username }}'
    ansible_password: '{{ password }}'
    command_to_run: 'show version' #settable


  tasks:
    - name:
      ios_command:
        commands: "{{ command_to_run }}"
      register: output
    
    - debug:
        var: output