---
- name: Playbook 
  hosts: localhost
  gather_facts: no
  connection: local

  vars:
   
    #logic.is_true
    #logic.is_false
    a_name: "{{workspace.name}}" #settables
    b_name: "{{workspace.telstra_project_id}}" #settables
    c_name: "{{workspace.customer_project_record_id}}" #settables
    d_name: "{{workspace.description}}" #settables

  tasks:

  # since the new_string variable has been assigned from var_string 
  # it can now be accessed directly
  
  
  # keys within the dictinoary are accessible
  - name: Display the output of the global variable dictionary 'a_name'
    debug:
      msg: "{{ a_name }}"

  - name: Display the output of the global variable dictionary 'b_name'
    debug:
      msg: "{{ b_name }}"

  - name: Display the output of the global variable dictionary 'c_name'
    debug:
      msg: "{{ c_name }}"

  - name: Display the output of the global variable dictionary 'd_name'
    debug:
      msg: "{{ d_name }}"

...